### ISSUE TITLE
Suggest a different package name

### ISSUE THREAD

**Issue by kcharter** [kimlew/java-rename-files#1]
This is very minor, but when you start a package name with a top-level domain name like `com`, it's usually a good idea to use a real domain name, but written backwards, as a prefix of your package name. So for example, since you own the domain `kimlew.com` you might use the package name

```
com.kimlew.javarenamefiles
```

or even

```
com.kimlew.renamefiles
```

where `com.kimlew` is the first part of the package name. This is meant to guarantee that you package name is unique, thought that's not a big deal for this little program.

Just a suggestion.

**Comment by kimlew** [comment]
@kcharter I've renamed the package name as you suggested so it is unique.
