### ISSUE TITLE
Method 'doesDirectoryExist' should be named differently

### ISSUE THREAD

**Issue by kcharter** [kimlew/java-rename-files#2]
https://github.com/kimlew/java-rename-files/blob/ac307a3819e00f3b77ddc24236b4b8684a11bd13/src/com/javarenamefiles/RenameFiles.java#L88

Ordinarily you name a method that returns a boolean after the condition that holds when the method returns `true`. The `doesDirectoryExist` method returns `true` if the directory does _not_ exist, so you get this confusing code in your `main` method:

```
if (doesDirectoryExist(startPathFileObject)) return;
```

so it looks like you're bailing out of the program when the directory exists.

I suggest either renaming, or changing the code in `doesDirectoryExist` so it returns `false` where it currently returns `true`, and vice-versa, and then changing the code in `main` to

```
if (!doesDirectoryExist(startPathFileObject)) return;
```

**Comment by kimlew** [comment]
Changed function name to directoryDoesNotExist() and made associated changes within method.
