### ISSUE TITLE
Unnecessary parameter in method 'renameAllFiles'

### ISSUE THREAD

**Issue by kcharter** [kimlew/java-rename-files#5]
https://github.com/kimlew/java-rename-files/blob/ac307a3819e00f3b77ddc24236b4b8684a11bd13/src/com/javarenamefiles/RenameFiles.java#L135-L141

I can't find anyplace in the body of `renameAllFiles` where you use the parameter `filesOfFileTypeArray`. I think you can remove that parameter.

**Comment by kimlew** [comment]
@kcharter I made the change.
